create or replace PROCEDURE insertCliente (
p_societa                     		   IN VARCHAR2, 
p_tipocodicecliente                    IN VARCHAR2, 
p_tipocodicepdc                        IN VARCHAR2, 
p_codicecliente                        IN VARCHAR2, 
p_codicepdc                            IN VARCHAR2, 
p_partitaivacliente                    IN VARCHAR2, 
p_codicefiscalecliente                 IN VARCHAR2, 
p_ragionebrevecliente                  IN VARCHAR2, 
p_ragionecliente                       IN VARCHAR2, 
p_indirizzocliente                     IN VARCHAR2, 
p_capcliente                           IN VARCHAR2, 
p_cittacliente                         IN VARCHAR2, 
p_provinciacliente                     IN VARCHAR2, 
p_areacliente                          IN VARCHAR2, 
p_zonacliente                          IN VARCHAR2, 
p_codicenazionecliente                 IN VARCHAR2, 
p_telefonocliente                      IN VARCHAR2, 
p_faxcliente                           IN VARCHAR2, 
p_cellularecliente                     IN VARCHAR2, 
p_telefono2cliente                     IN VARCHAR2, 
p_mailcliente                          IN VARCHAR2, 
p_codicelinguacliente                  IN VARCHAR2, 
p_codicetrasportocliente               IN VARCHAR2, 
p_codicevettorecliente                 IN VARCHAR2, 
p_codicecategoriacliente               IN VARCHAR2, 
p_descrizionecategoriacliente          IN VARCHAR2, 
p_codicecategoriapdc                   IN VARCHAR2, 
p_descrizionecategoriapdc              IN VARCHAR2, 
p_codicegruppocliente                  IN VARCHAR2, 
p_descrizionegruppocliente             IN VARCHAR2, 
p_codiceagentecliente                  IN VARCHAR2, 
p_tipoagentecliente                    IN VARCHAR2, 
p_progressivoagentecliente             IN NUMBER, 
p_codiceagente2cliente                 IN VARCHAR2, 
p_tipoagente2cliente                   IN VARCHAR2, 
p_progressivo2agentecliente            IN NUMBER, 
p_codiceagente3cliente                 IN VARCHAR2, 
p_tipoagente3cliente                   IN VARCHAR2, 
p_progressivo3agentecliente            IN NUMBER, 
p_codiceagente4cliente                 IN VARCHAR2, 
p_tipoagente4cliente                   IN VARCHAR2, 
p_progressivo4agentecliente            IN NUMBER, 
p_codiceagentepdc                      IN VARCHAR2, 
p_vecchiocodicecliente                 IN VARCHAR2, 
p_nuovocodicecliente                   IN VARCHAR2, 
p_codiceclienteunico                   IN VARCHAR2, 
p_attivazionecliente                   IN VARCHAR2, 
p_disdettacliente                      IN VARCHAR2, 
p_areamanagertecnico                   IN VARCHAR2, 
p_attivocliente                        IN NUMBER, 
p_attivopdc                            IN NUMBER, 
p_cessionecredito                      IN NUMBER, 
p_mail2cliente                         IN VARCHAR2, 
p_microarea                            IN VARCHAR2, 
p_microbrick                           IN VARCHAR2, 
p_codcliesterno                        IN VARCHAR2, 
p_latitudine                           IN VARCHAR2, 
p_longitudine                          IN VARCHAR2
)
AS
BEGIN
  INSERT INTO TB_CLIENTI_TMP
    (societa,
	tipo_cod_cli,
    tipo_codice_pdc,
    cod_cli,
    cod_pdc,
    partita_iva_cli,
    cod_fiscale_cli,
    ragione_sociale_breve_cli,
    ragione_sociale_cli,
    indirizzo_cli,
    cap_cli,
    citta_cli,
    provincia_cli,
    area_cli,
    zona_cli,
    cod_nazione_cli,
    telefono_cli,
    fax_cli,
    cellulare_cli,
    telefono2_cli,
    mail_cli,
    cod_lingua_cli,
    cod_trasporto_cli,
    cod_vettore_cli,
    cod_cat_cli,
    desc_cat_cli,
    cod_cat_pdc,
    desc_cat_pdc,
    cod_gruppo_cli,
    desc_gruppo_cli,
    cod_agn_cli,
    tipo_agn_cli,
    prog_agn_cli,
    cod_agn2_cli,
    tipo_agn2_cli,
    prog2_agn_cli,
    cod_agn3_cli,
    tipo_agn3_cli,
    prog3_agn_cli,
    cod_agn4_cli,
    tipo_agn4_cli,
    prog4_agn_cli,
	cod_agn_pdc,
	vecchio_cod_cli,
	nuovo_cod_cli,
	cod_cli_unico,
	attivazione_cli,
	disdetta_cli,
	amt,
	attivo_cli,
	attivo_pdc,
	cessione_credito,
	mail2_cli,
	microarea,
	microbrick,
	cod_cli_esterno,
	latitudine,
	longitudine)
  VALUES
   (p_societa,
	p_tipocodicecliente,
	p_tipocodicepdc,
	p_codicecliente,
	p_codicepdc,
	p_partitaivacliente,
	p_codicefiscalecliente,
	p_ragionebrevecliente,
	p_ragionecliente,
	p_indirizzocliente,
	p_capcliente,
	p_cittacliente,
	p_provinciacliente,
	p_areacliente,
	p_zonacliente,
	p_codicenazionecliente,
	p_telefonocliente,
	p_faxcliente,
	p_cellularecliente,
	p_telefono2cliente,
	p_mailcliente,
	p_codicelinguacliente,
	p_codicetrasportocliente,
	p_codicevettorecliente,
	p_codicecategoriacliente,
	p_descrizionecategoriacliente,
	p_codicecategoriapdc,
	p_descrizionecategoriapdc,
	p_codicegruppocliente,
	p_descrizionegruppocliente,
	p_codiceagentecliente,
	p_tipoagentecliente,
	p_progressivoagentecliente,
	p_codiceagente2cliente,
	p_tipoagente2cliente,
	p_progressivo2agentecliente,
	p_codiceagente3cliente,
	p_tipoagente3cliente,
	p_progressivo3agentecliente,
	p_codiceagente4cliente,
	p_tipoagente4cliente,
	p_progressivo4agentecliente,
	p_codiceagentepdc,
	p_vecchiocodicecliente,
	p_nuovocodicecliente,
	p_codiceclienteunico,
	p_attivazionecliente,
	p_disdettacliente,
	p_areamanagertecnico,
	p_attivocliente,
	p_attivopdc,
	p_cessionecredito,
	p_mail2cliente,
	p_microarea,
	p_microbrick,
	p_codcliesterno,
	p_latitudine,
	p_longitudine
    );
EXCEPTION
  WHEN OTHERS THEN
    HTP.print(SQLERRM);
END;